Starter EDA

# 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# 2. Loading the Datasets

In [2]:
# Load the dataset
r_df = pd.read_csv('real_instances.csv')
h_df = pd.read_csv('hand_drawn_instances.csv')
s_df = pd.read_csv('simulated_instances.csv')

In [5]:
pd.set_option('display.max_columns', None)

# 3. Understanding the Dataset

## 3.1 Preview the Data

In [7]:
# Display first dataset of real instances
r_df

,timestamp,label,well,id,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,ESTADO-XO,P-ANULAR,P-JUS-BS,P-JUS-CKGL,P-JUS-CKP,P-MON-CKGL,P-MON-CKP,P-MON-SDV-P,P-PDG,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state
0,2014-12-17 14:27:45,9,WELL-00042,20141217142745,23.0,38.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,18358740.0,NaN,16771370.0,NaN,NaN,2190777.0,NaN,18979920.0,NaN,10180070.0,NaN,3.032789,40.20570,NaN,74.58371,58.95389,NaN,NaN
1,2014-12-17 14:27:46,9,WELL-00042,20141217142745,23.0,38.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,18358910.0,NaN,16771360.0,NaN,NaN,2190779.0,NaN,18979930.0,NaN,10180060.0,NaN,3.033681,40.20566,NaN,74.58370,58.95395,NaN,NaN
2,2014-12-17 14:27:47,9,WELL-00042,20141217142745,23.0,38.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,18359070.0,NaN,16771360.0,NaN,NaN,2190780.0,NaN,18979940.0,NaN,10180050.0,NaN,3.034572,40.20562,NaN,74.58369,58.95401,NaN,NaN
3,2014-12-17 14:27:48,9,WELL-00042,20141217142745,23.0,38.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,18359240.0,NaN,16771350.0,NaN,NaN,2190781.0,NaN,18979950.0,NaN,10180040.0,NaN,3.035463,40.20559,NaN,74.58368,58.95407,NaN,NaN
4,2014-12-17 14:27:49,9,WELL-00042,20141217142745,23.0,38.0,NaN,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,18359400.0,NaN,16771350.0,NaN,NaN,2190782.0,NaN,18979960.0,NaN,10180040.0,NaN,3.036354,40.20555,NaN,74.58368,58.95413,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32872245,2014-03-20 04:20:34,5,WELL-00020,20140319110000,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,8937409.0,NaN,6356541.0,NaN,NaN,1311047.0,NaN,32308910.0,NaN,4631294.0,NaN,0.000000,31.23388,NaN,118.15850,87.30427,5.0,0.0
32872246,2014-03-20 04:20:35,5,WELL-00020,20140319110000,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,8937409.0,NaN,6356974.0,NaN,NaN,1310748.0,NaN,32308910.0,NaN,4630961.0,NaN,0.000000,31.23269,NaN,118.15850,87.30622,5.0,0.0
32872247,2014-03-20 04:20:36,5,WELL-00020,20140319110000,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,8937409.0,NaN,6357407.0,NaN,NaN,1310449.0,NaN,32308910.0,NaN,4630629.0,NaN,0.000000,31.23150,NaN,118.15850,87.30817,5.0,0.0
32872248,2014-03-20 04:20:37,5,WELL-00020,20140319110000,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,8937409.0,NaN,6357841.0,NaN,NaN,1310150.0,NaN,32308910.0,NaN,4630296.0,NaN,0.000000,31.23031,NaN,118.15850,87.31013,5.0,0.0
32872249,2014-03-20 04:20:38,5,WELL-00020,20140319110000,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,8937409.0,NaN,6358274.0,NaN,NaN,1309851.0,NaN,32308910.0,NaN,4629964.0,NaN,0.000000,31.22912,NaN,118.15850,87.31208,5.0,0.0

In [8]:
# Display second dataset of hand drawn instances 
h_df

,timestamp,label,well,id,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,ESTADO-XO,P-ANULAR,P-JUS-BS,P-JUS-CKGL,P-JUS-CKP,P-MON-CKGL,P-MON-CKP,P-MON-SDV-P,P-PDG,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state
0,2018-08-20 11:25:44,7,DRAWN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0578,NaN,260.0206,NaN,211.0180,NaN,NaN,65.4473,NaN,NaN,117.9769,0,0
1,2018-08-20 11:25:45,7,DRAWN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0578,NaN,260.0206,NaN,211.0180,NaN,NaN,65.4473,NaN,NaN,117.9769,0,0
2,2018-08-20 11:25:46,7,DRAWN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0578,NaN,260.0206,NaN,211.0180,NaN,NaN,65.4473,NaN,NaN,117.9769,0,0
3,2018-08-20 11:25:47,7,DRAWN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0578,NaN,260.0206,NaN,211.0180,NaN,NaN,65.4473,NaN,NaN,117.9769,0,0
4,2018-08-20 11:25:48,7,DRAWN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.0578,NaN,260.0206,NaN,211.0180,NaN,NaN,65.4473,NaN,NaN,117.9769,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2966405,2018-09-06 08:44:31,1,DRAWN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0437,NaN,415.5051,NaN,118.0514,NaN,NaN,74.8329,NaN,NaN,120.9152,101,0
2966406,2018-09-06 08:44:32,1,DRAWN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0437,NaN,415.5051,NaN,118.0514,NaN,NaN,74.8329,NaN,NaN,120.9152,101,0
2966407,2018-09-06 08:44:33,1,DRAWN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0437,NaN,415.5051,NaN,118.0514,NaN,NaN,74.8329,NaN,NaN,120.9152,101,0
2966408,2018-09-06 08:44:34,1,DRAWN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0437,NaN,415.5051,NaN,118.0514,NaN,NaN,74.8329,NaN,NaN,120.9152,101,0
2966409,2018-09-06 08:44:35,1,DRAWN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0437,NaN,415.5051,NaN,118.0514,NaN,NaN,74.8329,NaN,NaN,120.9152,101,0

In [9]:
# Display third dataset of simulated instances file
s_df

,timestamp,label,well,id,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,ESTADO-XO,P-ANULAR,P-JUS-BS,P-JUS-CKGL,P-JUS-CKP,P-MON-CKGL,P-MON-CKP,P-MON-SDV-P,P-PDG,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state
0,2018-09-29 06:18:19,9,SIMULATED,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21985960.0,NaN,NaN,1.216264e+06,NaN,1.975884e+07,NaN,9.031051e+06,NaN,4.746355,75.582123,NaN,NaN,90.806826,0,0
1,2018-09-29 06:18:20,9,SIMULATED,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21985960.0,NaN,NaN,1.216263e+06,NaN,1.975884e+07,NaN,9.031038e+06,NaN,4.746355,75.582113,NaN,NaN,90.806798,0,0
2,2018-09-29 06:18:21,9,SIMULATED,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21985960.0,NaN,NaN,1.216263e+06,NaN,1.975883e+07,NaN,9.031032e+06,NaN,4.746355,75.582103,NaN,NaN,90.806768,0,0
3,2018-09-29 06:18:22,9,SIMULATED,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21985967.2,NaN,NaN,1.216262e+06,NaN,1.975883e+07,NaN,9.031026e+06,NaN,4.746355,75.582093,NaN,NaN,90.806746,0,0
4,2018-09-29 06:18:23,9,SIMULATED,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21985970.0,NaN,NaN,1.216261e+06,NaN,1.975883e+07,NaN,9.031015e+06,NaN,4.746355,75.582083,NaN,NaN,90.806718,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40748653,2018-04-26 10:03:06,5,SIMULATED,389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189346.0,NaN,1.515686e+06,NaN,2.536780e+07,NaN,1.767330e+07,NaN,NaN,81.557550,83.509000,NaN,122.730676,5,0
40748654,2018-04-26 10:03:07,5,SIMULATED,389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189346.0,NaN,1.515686e+06,NaN,2.536758e+07,NaN,1.767426e+07,NaN,NaN,81.557550,83.509000,NaN,122.731158,5,0
40748655,2018-04-26 10:03:08,5,SIMULATED,389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189346.0,NaN,1.515686e+06,NaN,2.536691e+07,NaN,1.767100e+07,NaN,NaN,81.557550,83.509000,NaN,122.725654,5,0
40748656,2018-04-26 10:03:09,5,SIMULATED,389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189346.0,NaN,1.515686e+06,NaN,2.536630e+07,NaN,1.767292e+07,NaN,NaN,81.557550,83.509000,NaN,122.726898,5,0
40748657,2018-04-26 10:03:10,5,SIMULATED,389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1189346.0,NaN,1.515686e+06,NaN,2.536601e+07,NaN,1.767294e+07,NaN,NaN,81.557550,83.509009,NaN,122.727570,5,0

All files consisits of 33 columns.

Real instances: ~32 million rows.

Hand-drawn instances: ~3 million rows.

Simulated instances: ~40 million rows.

## 3.2 Data Types

In [16]:
# Get the data types of each DataFrame
r_dtypes = r_df.dtypes.to_frame('Real').reset_index()
h_dtypes = h_df.dtypes.to_frame('Hand-drawn').reset_index()
s_dtypes = s_df.dtypes.to_frame('Simulated').reset_index()

# Merge the data types DataFrames on column names
dtype_df = r_dtypes.merge(h_dtypes, on='index', how='outer').merge(s_dtypes, on='index', how='outer')

# Rename the 'index' column to 'Column'
dtype_df = dtype_df.rename(columns={'index': 'Column'})

# Reorder columns
dtype_df = dtype_df[['Column', 'Real', 'Hand-drawn', 'Simulated']]

# Display the data types comparison
print(dtype_df)

           Column     Real Hand-drawn Simulated
0       ABER-CKGL  float64    float64   float64
1        ABER-CKP  float64    float64   float64
2     ESTADO-DHSV  float64    float64   float64
3       ESTADO-M1  float64    float64   float64
4       ESTADO-M2  float64    float64   float64
5      ESTADO-PXO  float64    float64   float64
6   ESTADO-SDV-GL  float64    float64   float64
7    ESTADO-SDV-P  float64    float64   float64
8       ESTADO-W1  float64    float64   float64
9       ESTADO-W2  float64    float64   float64
10      ESTADO-XO  float64    float64   float64
11       P-ANULAR  float64    float64   float64
12       P-JUS-BS  float64    float64   float64
13     P-JUS-CKGL  float64    float64   float64
14      P-JUS-CKP  float64    float64   float64
15     P-MON-CKGL  float64    float64   float64
16      P-MON-CKP  float64    float64   float64
17    P-MON-SDV-P  float64    float64   float64
18          P-PDG  float64    float64   float64
19          P-TPT  float64    float64   float64
20           PT-P  float64    float64   float64
21            QBS  float64    float64   float64
22            QGL  float64    float64   float64
23      T-JUS-CKP  float64    float64   float64
24      T-MON-CKP  float64    float64   float64
25          T-PDG  float64    float64   float64
26          T-TPT  float64    float64   float64
27          class  float64      int64     int64
28             id    int64      int64     int64
29          label    int64      int64     int64
30          state  float64      int64     int64
31      timestamp   object     object    object
32           well   object     object    object

All columns across the 3 dataset have the same data type

###  Downcasting the data types to avoid out  of memory issues

In [24]:
def optimize_dtypes(df):
    for col in df.columns:
        col_type = df[col].dtype

        if col_type == 'int64' or col_type == 'int32':
            c_min = df[col].min()
            c_max = df[col].max()
            if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                df[col] = df[col].astype(np.int8)
            elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                df[col] = df[col].astype(np.int16)
            else:
                df[col] = df[col].astype(np.int32)
        elif col_type == 'float64' or col_type == 'float32':
            c_min = df[col].min()
            c_max = df[col].max()
            if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                df[col] = df[col].astype(np.float16)
            else:
                df[col] = df[col].astype(np.float32)
    return df

# Apply to your DataFrames
r_df = optimize_dtypes(r_df)
h_df = optimize_dtypes(h_df)
s_df = optimize_dtypes(s_df)

C:\Users\ma123\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py:133: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)

## 3.3 Statistical Summary

In [18]:
# Generate the statistical summaries for each dataset
r_desc = r_df.describe().transpose()
h_desc = h_df.describe().transpose()
s_desc = s_df.describe().transpose()

# Add a column to identify the dataset
r_desc['Dataset'] = 'Real'
h_desc['Dataset'] = 'Hand-drawn'
s_desc['Dataset'] = 'Simulated'

# Add an index to identify the features
r_desc['Feature'] = r_desc.index
h_desc['Feature'] = h_desc.index
s_desc['Feature'] = s_desc.index

# Combine the summaries into one DataFrame
combined_desc = pd.concat([r_desc, h_desc, s_desc], axis=0)

# Rearrange columns for better readability
combined_desc = combined_desc[['Feature', 'Dataset', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]

# Pivot the DataFrame to compare datasets side by side
pivot_desc = combined_desc.pivot(index='Feature', columns='Dataset')

# Flatten the MultiIndex columns
pivot_desc.columns = ['_'.join(col).strip() for col in pivot_desc.columns.values]

# Reset index to turn 'Feature' back into a column
pivot_desc = pivot_desc.reset_index()

# Display the combined summary
print(pivot_desc)

          Feature  count_Hand-drawn  count_Real  count_Simulated  \
0       ABER-CKGL               0.0   8491513.0              0.0
1        ABER-CKP               0.0  12326458.0              0.0
2     ESTADO-DHSV               0.0  13865397.0              0.0
3       ESTADO-M1               0.0  17773205.0              0.0
4       ESTADO-M2               0.0  17688282.0              0.0
5      ESTADO-PXO               0.0  18176203.0              0.0
6   ESTADO-SDV-GL               0.0  17105271.0              0.0
7    ESTADO-SDV-P               0.0  24316107.0              0.0
8       ESTADO-W1               0.0  18938036.0              0.0
9       ESTADO-W2               0.0  18293462.0              0.0
10      ESTADO-XO               0.0  18538730.0              0.0
11       P-ANULAR               0.0  25460515.0              0.0
12       P-JUS-BS               0.0         0.0              0.0
13     P-JUS-CKGL               0.0  25050379.0        6845855.0
14      P-JUS-CKP               0.0   3448901.0       18667059.0
15     P-MON-CKGL               0.0    308726.0              0.0
16      P-MON-CKP         2966410.0  25792399.0       40748658.0
17    P-MON-SDV-P               0.0         0.0              0.0
18          P-PDG         2966410.0  24956034.0       40748658.0
19          P-TPT         2966410.0  27490467.0       40748658.0
20           PT-P               0.0         0.0              0.0
21            QBS               0.0         0.0              0.0
22            QGL               0.0  17720105.0        6845855.0
23      T-JUS-CKP         2966410.0  16839350.0       40748658.0
24      T-MON-CKP               0.0   4950546.0       18667059.0
25          T-PDG               0.0  20811272.0              0.0
26          T-TPT         2966410.0  28415000.0       34943868.0
27          class         2966410.0  28843850.0       40748658.0
28             id         2966410.0  32872250.0       40748658.0
29          label         2966410.0  32872250.0       40748658.0
30          state         2966410.0  28843850.0       40748658.0

    mean_Hand-drawn     mean_Real  mean_Simulated  std_Hand-drawn  \
0               NaN  1.931843e+01             NaN             NaN
1               NaN  4.052591e+01             NaN             NaN
2               NaN  5.703575e-01             NaN             NaN
3               NaN  8.532889e-01             NaN             NaN
4               NaN  3.172376e-01             NaN             NaN
5               NaN  8.822910e-03             NaN             NaN
6               NaN  5.448040e-01             NaN             NaN
7               NaN  9.110019e-01             NaN             NaN
8               NaN  7.026502e-01             NaN             NaN
9               NaN  2.407879e-01             NaN             NaN
10              NaN  3.095789e-03             NaN             NaN
11              NaN  1.516698e+07             NaN             NaN
12              NaN           NaN             NaN             NaN
13              NaN  1.080966e+07    3.787256e+07             NaN
14              NaN  5.275017e+08    1.896856e+06             NaN
15              NaN  9.670924e+06             NaN             NaN
16        35.155431  4.616269e+06    2.832020e+06       29.210109
17              NaN           NaN             NaN             NaN
18       270.053534 -1.445489e+40    2.284655e+07       55.707233
19       136.927548  1.648637e+07    1.465532e+07       34.485794
20              NaN           NaN             NaN             NaN
21              NaN           NaN             NaN             NaN
22              NaN  1.058164e+00    1.941351e+00             NaN
23        58.294032  5.951102e+01    7.409007e+01        7.454988
24              NaN  1.511980e+01    8.519754e+01             NaN
25              NaN -2.514042e+36             NaN             NaN
26        78.155658  8.277202e+01    1.023605e+02       24.640260
27        88.767676  4.136475e+01    3.572578e+01       38.772996
28         4.490295  2.017152e+13    1.157407e+02        2.655351
29         5.893208  4.183155e+00    4.915195e+00        2.327180
30         0.000000  2.706468e-01    0.000000e+00        0.000000

        std_Real  std_Simulated  min_Hand-drawn      min_Real  min_Simulated  \
0   3.040067e+01            NaN             NaN  0.000000e+00            NaN
1   3.259661e+01            NaN             NaN -9.999000e+01            NaN
2   4.950251e-01            NaN             NaN  0.000000e+00            NaN
3   3.538177e-01            NaN             NaN  0.000000e+00            NaN
4   4.653943e-01            NaN             NaN  0.000000e+00            NaN
5   9.351506e-02            NaN             NaN  0.000000e+00            NaN
6   4.979886e-01            NaN             NaN  0.000000e+00            NaN
7   2.847410e-01            NaN             NaN  0.000000e+00            NaN
8   4.570918e-01            NaN             NaN  0.000000e+00            NaN
9   4.275589e-01            NaN             NaN  0.000000e+00            NaN
10  5.555363e-02            NaN             NaN  0.000000e+00            NaN
11  6.601109e+06            NaN             NaN -7.658084e+06            NaN
12           NaN            NaN             NaN           NaN            NaN
13  7.589678e+06   1.564886e+08             NaN -4.976717e+05   1.215353e+07
14  6.815282e+08   2.160906e+06             NaN -9.999000e+06   9.907910e+05
15  7.609565e+06            NaN             NaN -9.400000e+04            NaN
16  3.581677e+06   2.641771e+06       10.047560 -2.370260e+05   4.471283e+05
17           NaN            NaN             NaN           NaN            NaN
18  1.298056e+41   4.824392e+06      120.359900 -1.180116e+42   6.803295e+06
19  8.850289e+07   4.538620e+06       19.074550 -1.712930e+07   3.465769e+06
20           NaN            NaN             NaN           NaN            NaN
21           NaN            NaN             NaN           NaN            NaN
22  1.120481e+00   2.171400e+00             NaN  0.000000e+00  -5.417673e+01
23  1.314570e+01   1.978197e+01       30.030850 -1.139319e+01  -1.772124e+00
24  2.400158e+01   1.127157e+01             NaN -9.999000e+01   2.374291e+01
25  2.059093e+37            NaN             NaN -1.711613e+38            NaN
26  4.438037e+01   2.708771e+01        5.710797 -3.375000e+01   2.954238e+00
27  5.174717e+01   4.654560e+01        0.000000  0.000000e+00   0.000000e+00
28  1.795104e+10   1.081930e+02        1.000000  2.011083e+13   1.000000e+00
29  3.539022e+00   2.663610e+00        1.000000  0.000000e+00   1.000000e+00
30  1.120948e+00   0.000000e+00        0.000000  0.000000e+00   0.000000e+00

    25%_Hand-drawn      25%_Real  25%_Simulated  50%_Hand-drawn      50%_Real  \
0              NaN  0.000000e+00            NaN             NaN  0.000000e+00
1              NaN  2.852520e+01            NaN             NaN  3.928209e+01
2              NaN  0.000000e+00            NaN             NaN  1.000000e+00
3              NaN  1.000000e+00            NaN             NaN  1.000000e+00
4              NaN  0.000000e+00            NaN             NaN  0.000000e+00
5              NaN  0.000000e+00            NaN             NaN  0.000000e+00
6              NaN  0.000000e+00            NaN             NaN  1.000000e+00
7              NaN  1.000000e+00            NaN             NaN  1.000000e+00
8              NaN  0.000000e+00            NaN             NaN  1.000000e+00
9              NaN  0.000000e+00            NaN             NaN  0.000000e+00
10             NaN  0.000000e+00            NaN             NaN  0.000000e+00
11             NaN  9.249301e+06            NaN             NaN  1.491015e+07
12             NaN           NaN            NaN             NaN           NaN
13             NaN  2.807992e+06   3.109472e+07             NaN  1.309580e+07
14             NaN  1.185471e+06   1.080128e+06             NaN  1.789070e+06
15             NaN  8.762333e+05            NaN             NaN  1.474788e+07
16       13.710013  1.886164e+06   1.111839e+06       21.605400  3.752566e+06
17             NaN           NaN            NaN             NaN           NaN
18      250.172200  0.000000e+00   1.988147e+07      251.774785  0.000000e+00
19      118.247311  8.821826e+06   1.160623e+07      135.745500  1.359211e+07
20             NaN           NaN            NaN             NaN           NaN
21             NaN           NaN            NaN             NaN           NaN
22             NaN  0.000000e+00   6.986431e-03             NaN  1.004557e+00
23       52.034700  5.397870e+01   6.966859e+01       57.546270  5.747213e+01
24             NaN  3.548337e+00   8.250681e+01             NaN  2.364015e+01
25             NaN  0.000000e+00            NaN             NaN  3.623471e+01
26       59.874040  5.143106e+01   9.390779e+01       64.821340  1.058377e+02
27      101.000000  0.000000e+00   5.000000e+00      107.000000  0.000000e+00
28        2.000000  2.017021e+13   3.800000e+01        5.000000  2.017063e+13
29        7.000000  0.000000e+00   3.000000e+00        7.000000  4.000000e+00
30        0.000000  0.000000e+00   0.000000e+00        0.000000  0.000000e+00

    50%_Simulated  75%_Hand-drawn      75%_Real  75%_Simulated  \
0             NaN             NaN  4.500000e+01            NaN
1             NaN             NaN  4.286402e+01            NaN
2             NaN             NaN  1.000000e+00            NaN
3             NaN             NaN  1.000000e+00            NaN
4             NaN             NaN  1.000000e+00            NaN
5             NaN             NaN  0.000000e+00            NaN
6             NaN             NaN  1.000000e+00            NaN
7             NaN             NaN  1.000000e+00            NaN
8             NaN             NaN  1.000000e+00            NaN
9             NaN             NaN  0.000000e+00            NaN
10            NaN             NaN  0.000000e+00            NaN
11            NaN             NaN  2.121720e+07            NaN
12            NaN             NaN           NaN            NaN
13   3.499999e+07             NaN  1.783144e+07   3.999997e+07
14   1.117737e+06             NaN  1.369742e+09   1.181166e+06
15            NaN             NaN  1.727167e+07            NaN
16   1.359531e+06       46.716600  6.105821e+06   4.043755e+06
17            NaN             NaN           NaN            NaN
18   2.307977e+07      256.170013  2.245869e+07   2.616428e+07
19   1.489549e+07      159.624610  2.074822e+07   1.718335e+07
20            NaN             NaN           NaN            NaN
21            NaN             NaN           NaN            NaN
22   9.496842e-01             NaN  1.975181e+00   3.705405e+00
23   7.929659e+01       63.128110  6.838226e+01   8.584572e+01
24   8.667026e+01             NaN  2.636000e+01   9.121917e+01
25            NaN             NaN  7.431699e+01            NaN
26   1.082476e+02      109.951200  1.169890e+02   1.226074e+02
27   5.000000e+00      107.000000  1.070000e+02   1.010000e+02
28   7.800000e+01        7.000000  2.018083e+13   1.510000e+02
29   5.000000e+00        7.000000  7.000000e+00   6.000000e+00
30   0.000000e+00        0.000000  0.000000e+00   0.000000e+00

    max_Hand-drawn      max_Real  max_Simulated
0              NaN  1.000000e+02            NaN
1              NaN  1.004375e+02            NaN
2              NaN  1.000000e+00            NaN
3              NaN  1.000000e+00            NaN
4              NaN  1.000000e+00            NaN
5              NaN  1.000000e+00            NaN
6              NaN  1.000000e+00            NaN
7              NaN  1.000000e+00            NaN
8              NaN  1.000000e+00            NaN
9              NaN  1.000000e+00            NaN
10             NaN  1.000000e+00            NaN
11             NaN  4.349212e+07            NaN
12             NaN           NaN            NaN
13             NaN  4.006530e+07   1.052061e+10
14             NaN  1.559396e+09   1.005177e+07
15             NaN  2.622300e+07            NaN
16        122.9152  2.474700e+07   1.303717e+07
17             NaN           NaN            NaN
18        429.8329  4.909435e+07   3.888753e+07
19        211.8869  2.941990e+09   3.251330e+07
20             NaN           NaN            NaN
21             NaN           NaN            NaN
22             NaN  4.310789e+00   7.297315e+00
23         74.8329  8.548460e+01   1.111957e+02
24             NaN  1.112300e+02   1.102682e+02
25             NaN  3.000000e+04            NaN
26        123.6003  1.196061e+02   1.277401e+02
27        107.0000  1.090000e+02   1.090000e+02
28         10.0000  2.023092e+13   4.390000e+02
29          7.0000  9.000000e+00   9.000000e+00
30          0.0000  8.000000e+00   0.000000e+00

## 3.4 Missing Values

In [19]:
# Calculate the number of missing values in each dataset
r_missing = r_df.isnull().sum().to_frame('Real')
h_missing = h_df.isnull().sum().to_frame('Hand-drawn')
s_missing = s_df.isnull().sum().to_frame('Simulated')

# Combine the missing values data
missing_values = r_missing.join(h_missing, how='outer').join(s_missing, how='outer')

# Reset index to have 'Feature' column
missing_values = missing_values.rename_axis('Feature').reset_index()

# Display the missing values comparison
print(missing_values)

          Feature      Real  Hand-drawn  Simulated
0       ABER-CKGL  24380737     2966410   40748658
1        ABER-CKP  20545792     2966410   40748658
2     ESTADO-DHSV  19006853     2966410   40748658
3       ESTADO-M1  15099045     2966410   40748658
4       ESTADO-M2  15183968     2966410   40748658
5      ESTADO-PXO  14696047     2966410   40748658
6   ESTADO-SDV-GL  15766979     2966410   40748658
7    ESTADO-SDV-P   8556143     2966410   40748658
8       ESTADO-W1  13934214     2966410   40748658
9       ESTADO-W2  14578788     2966410   40748658
10      ESTADO-XO  14333520     2966410   40748658
11       P-ANULAR   7411735     2966410   40748658
12       P-JUS-BS  32872250     2966410   40748658
13     P-JUS-CKGL   7821871     2966410   33902803
14      P-JUS-CKP  29423349     2966410   22081599
15     P-MON-CKGL  32563524     2966410   40748658
16      P-MON-CKP   7079851           0          0
17    P-MON-SDV-P  32872250     2966410   40748658
18          P-PDG   7916216           0          0
19          P-TPT   5381783           0          0
20           PT-P  32872250     2966410   40748658
21            QBS  32872250     2966410   40748658
22            QGL  15152145     2966410   33902803
23      T-JUS-CKP  16032900           0          0
24      T-MON-CKP  27921704     2966410   22081599
25          T-PDG  12060978     2966410   40748658
26          T-TPT   4457250           0    5804790
27          class   4028400           0          0
28             id         0           0          0
29          label         0           0          0
30          state   4028400           0          0
31      timestamp         0           0          0
32           well         0           0          0

### 3.4.1 Missing Values %%

In [20]:
# Function to calculate missing value percentages
def missing_percentage(df, dataset_name):
    total = df.shape[0]
    missing_count = df.isnull().sum()
    missing_percent = (missing_count / total) * 100
    return missing_percent.to_frame(dataset_name)

# Calculate missing percentages for each dataset
r_missing_pct = missing_percentage(r_df, 'Real')
h_missing_pct = missing_percentage(h_df, 'Hand-drawn')
s_missing_pct = missing_percentage(s_df, 'Simulated')

# Combine the percentages
missing_percentages = r_missing_pct.join(h_missing_pct).join(s_missing_pct)
missing_percentages = missing_percentages.rename_axis('Feature').reset_index()

# Display the missing percentages
print(missing_percentages)

          Feature        Real  Hand-drawn   Simulated
0       timestamp    0.000000         0.0    0.000000
1           label    0.000000         0.0    0.000000
2            well    0.000000         0.0    0.000000
3              id    0.000000         0.0    0.000000
4       ABER-CKGL   74.168142       100.0  100.000000
5        ABER-CKP   62.501934       100.0  100.000000
6     ESTADO-DHSV   57.820359       100.0  100.000000
7       ESTADO-M1   45.932496       100.0  100.000000
8       ESTADO-M2   46.190839       100.0  100.000000
9      ESTADO-PXO   44.706544       100.0  100.000000
10  ESTADO-SDV-GL   47.964405       100.0  100.000000
11   ESTADO-SDV-P   26.028468       100.0  100.000000
12      ESTADO-W1   42.388988       100.0  100.000000
13      ESTADO-W2   44.349833       100.0  100.000000
14      ESTADO-XO   43.603708       100.0  100.000000
15       P-ANULAR   22.547088       100.0  100.000000
16       P-JUS-BS  100.000000       100.0  100.000000
17     P-JUS-CKGL   23.794754       100.0   83.199803
18      P-JUS-CKP   89.508169       100.0   54.189758
19     P-MON-CKGL   99.060831       100.0  100.000000
20      P-MON-CKP   21.537470         0.0    0.000000
21    P-MON-SDV-P  100.000000       100.0  100.000000
22          P-PDG   24.081759         0.0    0.000000
23           PT-P  100.000000       100.0  100.000000
24          P-TPT   16.371812         0.0    0.000000
25            QBS  100.000000       100.0  100.000000
26            QGL   46.094031       100.0   83.199803
27      T-JUS-CKP   48.773357         0.0    0.000000
28      T-MON-CKP   84.940045       100.0   54.189758
29          T-PDG   36.690455       100.0  100.000000
30          T-TPT   13.559309         0.0   14.245353
31          class   12.254713         0.0    0.000000
32          state   12.254713         0.0    0.000000

## 3.5 Duplicate Values

In [25]:
# Count duplicate rows in each dataset
r_duplicates = r_df.duplicated().sum()
h_duplicates = h_df.duplicated().sum()
s_duplicates = s_df.duplicated().sum()

# Create a DataFrame to display the counts
duplicate_counts = pd.DataFrame({
    'Dataset': ['Real', 'Hand-drawn', 'Simulated'],
    'Duplicate Rows': [r_duplicates, h_duplicates, s_duplicates]
})

print(duplicate_counts)

      Dataset  Duplicate Rows
0        Real               0
1  Hand-drawn               0
2   Simulated               0